INSERT INTO activities(activ_title)
VALUES
    ('Aikido'),
    ('Ballooning'),
    ('Gliding'), 
    ('Hang Gliding'), 
    ('Parachuting/Skydiving'),
    ('Airsoft'),
    ('Alpine Skiing'),
    ('Swimming'),
    ('Diving'), 
    ('Synchronized Swimming'), 
    ('Water Polo'),
    ('Open Water Swimming'),
    ('Archery'),
    ('Arm Wrestling'),
    ('Athletics'),
    ('Track and Field'), 
    ('Road Running'), 
    ('Cross Country Running'), 
    ('Decathlon'),
    ('Racewalking'),
    ('Australian rules football'),
    ('Auto Racing'),
    ('Badminton'),
    ('Bandy'),
    ('Baseball'),
    ('Softball'),
    ('Basketball'),
    ('Basque pelota'),
    ('Beach Soccer'),
    ('Behcup'),
    ('Biathlon'),
    ('Billiard Sports'),
    ('Bobsleigh and skeleton'),
    ('Bocce'),
    ('Boccia'),
    ('Bodyboarding'),
    ('Bodybuilding'),
    ('Boot Throwing'),
    ('Boule Lyonnaise'),
    ('Boules Sports'),
    ('Bowling (Canadian five-pin)'),
    ('Bowling (Ten-pin)'),
    ('Bowls'),
    ('Bowls'),
    ('Boxing'),
    ('Boxing (amateur)'),
    ('Bridge'),
    ('Broomball'),
    ('Canoeing'),
    ('Casting'),
    ('Chess'),
    ('Cricket'),
    ('Croquet'),
    ('Curling'),
    ('Cycling'),
    ('DanceSport'),
    ('Darts'),
    ('Dragon Boat Racing'),
    ('Draughts'),
    ('Elephant Polo'),
    ('Equestrian'),
    ('Fencing'),
    ('Fishing'),
    ('Fistball'),
    ('Floorball'),
    ('Flying Disc'),
    ('Foosball'),
    ('Frisbee Golf'),
    ('Football (AmericanandCanadian)'),
    ('Football (Gaelic)'),
    ('Game Fishing'),
    ('Go'),
    ('Goalball'),
    ('Golf'),
    ('Greyhound racing'),
    ('Gymnastics'), 
    ('Gymnastics(Rhythmic)'), 
    ('Gymnastics(Aerobics)'), 
    ('Gymnastics(Trampolining)'),
    ('Gymnastics(Tumbling)'),
    ('Handball (court)'),
    ('Handball (team)'),
    ('Hapkido Boxing'),
    ('Harness Horse Racing'),
    ('Lacrosse/Hockey(field)'),
    ('Horse Racing'),
    ('Horseshoes'),
    ('Hurling'),
    ('Ice hockey'),
    ('Figure Skating'),
    ('Speed Skating'),
    ('Short-track speed skating'),
    ('Judo'),
    ('Ju-Jitsu'),
    ('Kabaddi'),
    ('Karate'),
    ('Kendo'),
    ('Kickboxing,Muay Thai, San Shou'),
    ('Korfball'),
    ('Kung Fu'),
    ('Lacrosse'),
    ('Luge'),
    ('Mallakhamb'),
    ('Military Sports'),
    ('Miniature golf'),
    ('Mixed martial arts'),
    ('Modern pentathlon'),
    ('Motorcycle sport'),
    ('Mountain running'),
    ('Mountainboarding'),
    ('Mountaineering'),
    ('Muay Thai'),
    ('Netball'),
    ('Nordic Skiing(Biathlon)'),
    ('Nordic Sking(Cross-Country)'),
    ('Orienteering'),
    ('Paddleball'),
    ('Parkour'),
    ('Pesäpallo'),
    ('Petanque'),
    ('Pigeon racing'),
    ('Pitch and Putt'),
    ('Pole dance'),
    ('Polo'),
    ('Powerboating'),
    ('Powerlifting'),
    ('Practical shooting'),
    ('Quidditch'),
    ('Racketlon'),
    ('Racquetball'),
    ('Radio-controlled car racing'),
    ('Rafting'),
    ('Rogaining'),
    ('Roller Hockey'),
    ('Roller derby'),
    ('Rope Skipping'),
    ('Rounders'),
    ('Rowing'),
    ('Rugby Fives'),
    ('Rugby league'),
    ('Rugby union'),
    ('Sailing'),
    ('Sambo'),
    ('Sepak Takraw'),
    ('Shinty'),
    ('Shooting'),
    ('Shuttlecock'),
    ('Skateboarding'),
    ('Ski mountaineering'),
    ('Skibobbing'),
    ('Skiing(Alpine)'),
    ('Skiing(Freestyle'),
    ('Ski Jumping'),
    ('Sled Dog Sports'),
    ('Soft Tennis'),
    ('Sports Climbing'),
    ('Sports Fishing'),
    ('Squash'),
    ('Sumo'),
    ('Surfing'),
    ('Bodyboarding'),
    ('Swimming'),
    ('Table hockey'),
    ('Table Soccer'),
    ('Table Tennis'),
    ('Taekwondo'),
    ('Tchoukball'),
    ('Tennis'),
    ('Tent Pegging'),
    ('Throwball'),
    ('Touch football'),
    ('Triathlon'),
    ('Tug-of-war'),
    ('Underwater sports'),
    ('Volleyball'),
    ('Beach volleyball'),
    ('Vovinam'),
    ('VX (Rock-It-Ball)'),
    ('Water skiing'),
    ('Weightlifting'),
    ('Wheelchair basketball'),
    ('Wheelchair curling'),
    ('Wheelchair Dance Sport'),
    ('Wheelchair Fencing'),
    ('Wheelchair rugby'),
    ('Wheelchair tennis'),
    ('Wrestling'),
    ('Wushu'),
    ('Yoga');